name: sipencari_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  dio: ^4.0.6
  location: ^4.2.0
  email_validator: ^2.1.17
  google_fonts: ^3.0.1
  carousel_slider: ^4.2.1
  responsive_framework: ^0.2.0
  percent_indicator: ^4.2.2
  provider: ^6.0.4
  sliding_up_panel: ^2.0.0+1
  open_file: ^3.2.1
  url_launcher: ^6.1.7
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.0.15
  slide_countdown: ^0.3.4
  badges: ^2.0.3
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_native_splash: ^2.2.11
  flutter:
    sdk: flutter
  fluentui_system_icons: ^1.1.190
  fluttertoast: ^8.1.2
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  sticky_headers: ^0.3.0+2
  dropdown_button2: ^1.9.2
  permission_handler: ^10.2.0
  device_info_plus: ^4.0.0
  image_picker: ^0.8.6+1
  geocoding: ^2.0.5
  after_layout: ^1.2.0
  timeago: ^3.3.0
  cached_network_image: ^3.2.3
  flutter_polyline_points: ^1.0.0
  photo_view: ^0.14.0
  http: ^0.13.4
  flutter_cache_manager: ^3.2.0
  flutter_slidable: ^3.0.0
  maps_launcher: ^2.2.0
  webview_flutter_plus: ^0.3.0+2
  dev_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter_native_splash:
  image: assets/splash.png
  color: "#ffffff"
  android_12:
    image: assets/splash.png
    color: "#ffffff"
  android: false
  ios: false

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/circle_big_logo.png"
  min_sdk_android: 16 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/circle_big_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/circle_big_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/circle_big_logo.png"

flutter:
  uses-material-design: true


  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf
